Deploy Azure Resources

diff --git a/.github/workflows/deploy-IaC.yml b/.github/workflows/deploy-IaC.yml
--- a/.github/workflows/deploy-IaC.yml
+++ b/.github/workflows/deploy-IaC.yml
@@ -34,42 +34,42 @@ jobs:
 
       - name: Terraform Fmt
         id: fmt
+        run: terraform fmt
+
+      - name: Terraform Init
+        id: init
+        run: |
+          terraform init \
+            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
+            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
+            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
+            -backend-config="access_key=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}" \
+            -backend-config="key=terraform.tfstate"
+
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate -no-color
+
+      - name: Terraform Plan
+        id: plan
+        run: |
+          export exitcode=0
+          terraform plan -no-color -var-file="terraform.tfvars" -out main.tfplan || export exitcode=$?
+
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+
+          if [ $exitcode -eq 1 ]; then
+            echo "Error: Terraform plan failed"
+            exit 1
+          else
+            echo "Terraform plan was successful"
+            exit 0
+          fi
+
+      - name: Terraform Apply
         run: terraform destroy
-#
-#      - name: Terraform Init
-#        id: init
-#        run: |
-#          terraform init \
-#            -backend-config="resource_group_name=${{ secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME }}" \
-#            -backend-config="storage_account_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME }}" \
-#            -backend-config="container_name=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME }}" \
-#            -backend-config="access_key=${{ secrets.BACKEND_AZURE_STORAGE_ACCOUNT_ACCESS_KEY }}" \
-#            -backend-config="key=terraform.tfstate"
-#
-#      - name: Terraform Validate
-#        id: validate
-#        run: terraform validate -no-color
-#
-#      - name: Terraform Plan
-#        id: plan
-#        run: |
-#          export exitcode=0
-#          terraform plan -no-color -var-file="terraform.tfvars" -out main.tfplan || export exitcode=$?
-#
-#          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
-#
-#          if [ $exitcode -eq 1 ]; then
-#            echo "Error: Terraform plan failed"
-#            exit 1
-#          else
-#            echo "Terraform plan was successful"
-#            exit 0
-#          fi
-#
-#      - name: Terraform Apply
-#        run: terraform apply -auto-approve "./main.tfplan"
-#
-#
+
+
 
 
 
